version: 0.2

phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Updating "latest" image tag in ECR...
      - aws ecr describe-images --repository-name $IMAGE_REPO_NAME --image-ids imageTag=latest --query 'images[0].imageDigest' --output text > image-digest.txt
      - IMAGE_DIGEST=$(cat image-digest.txt)
      - NEW_TAG="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
      - docker tag $IMAGE_DIGEST "$NEW_TAG"
      - docker push "$NEW_TAG"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Updating ECS service...
      - aws ecs update-service --cluster DockerECStest-Clustertest4C582AF6-55VC8GGsQE2Q --service DockerECStest-ServicetestServiceF60B2328-Ab4i5CUhQeEP --force-new-deployment
      #
